# Dockerfile
FROM ubuntu:latest

# Install necessary tools
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    wget \
    git \
    python3-pip \
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y nodejs

# Install Terraform
RUN curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_arm64.zip -o terraform.zip \
    && unzip terraform.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform.zip

# Install CDK for Terraform
RUN npm install -g cdktf-cli && npm install -g @cdktf/provider-aws

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

# Install AWS Local
RUN pip install awscli-local

# RUN git clone https://github.com/klhuang0504/CDKTF_LocalStack.git
    # && cd CDKTF_LocalStack && npm install @cdktf/provider-aws